services:
  freechess:
    build: ..
    container_name: freechess
    user: "${HOST_UID}:${HOST_GID}"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    entrypoint: /bin/sh -c "npm install && npm run ${COMMAND}"
