services:
  freechess:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: freechess:0.1.0
    container_name: freechess
    ports:
      - "10080:80"
      - "10443:443"
    volumes:
      - ./certs/freechess.org.pem.autosigned:/etc/letsencrypt/live/freechess.org/fullchain.pem
      - ./certs/freechess.org.key.autosigned:/etc/letsencrypt/live/freechess.org/privkey.pem
